// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using haulages_bot.Data;

#nullable disable

namespace haulages_bot.Migrations
{
    [DbContext(typeof(dbboot))]
    [Migration("20260904040759_AddDecimalPrecision")]
    partial class AddDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("haulages_bot.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId", "ServerConfigId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("haulages_bot.Models.DataConfigurationLocal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SelectedEmployees")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedRoutes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedVehicles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TonnageVariation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataConfigurationLocal");
                });

            modelBuilder.Entity("haulages_bot.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaternalLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NoEmployee")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("PaternalLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId", "ServerConfigId");

                    b.HasIndex("CompanyId", "ServerConfigId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("haulages_bot.Models.Haulage", b =>
                {
                    b.Property<int?>("HaulageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("HaulageId"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dateofcarries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId1")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeServerConfigId")
                        .HasColumnType("int");

                    b.Property<int?>("HaulagePathServerConfigId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Kilometers")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("LawType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoadPointId")
                        .HasColumnType("int");

                    b.Property<string>("LoadPointName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaterialTypeeServerConfigId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialTypeematerialTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PathId")
                        .HasColumnType("int");

                    b.Property<string>("RouteDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int?>("UnloadPointId")
                        .HasColumnType("int");

                    b.Property<string>("UnloadPointName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleEconomicNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleNavigationServerConfigId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleNavigationVehicleId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("haulagePathId")
                        .HasColumnType("int");

                    b.Property<int?>("materialTypeId")
                        .HasColumnType("int");

                    b.HasKey("HaulageId");

                    b.HasIndex("EmployeeId1", "EmployeeServerConfigId");

                    b.HasIndex("MaterialTypeematerialTypeId", "MaterialTypeeServerConfigId");

                    b.HasIndex("VehicleNavigationVehicleId", "VehicleNavigationServerConfigId");

                    b.HasIndex("haulagePathId", "HaulagePathServerConfigId");

                    b.ToTable("Haulages");
                });

            modelBuilder.Entity("haulages_bot.Models.Historic", b =>
                {
                    b.Property<int>("HistoricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoricId"));

                    b.Property<string>("Dateofcarries")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeServerConfigId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HaulagePathServerConfigId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialTypeServerConfigId")
                        .HasColumnType("int");

                    b.Property<int>("TokenRegistryId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleNavigationServerConfigId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleNavigationVehicleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("WorkShiftId")
                        .HasColumnType("int");

                    b.Property<int>("WorkShiftId1")
                        .HasColumnType("int");

                    b.Property<int>("WorkShiftServerConfigId")
                        .HasColumnType("int");

                    b.Property<int>("haulagePathId")
                        .HasColumnType("int");

                    b.Property<string>("loadPointName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("materialTypeId")
                        .HasColumnType("int");

                    b.Property<int>("materialTypeId1")
                        .HasColumnType("int");

                    b.Property<string>("unLoadPointName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HistoricId");

                    b.HasIndex("TokenRegistryId");

                    b.HasIndex("EmployeeId", "EmployeeServerConfigId");

                    b.HasIndex("VehicleNavigationVehicleId", "VehicleNavigationServerConfigId");

                    b.HasIndex("WorkShiftId1", "WorkShiftServerConfigId");

                    b.HasIndex("haulagePathId", "HaulagePathServerConfigId");

                    b.HasIndex("materialTypeId1", "MaterialTypeServerConfigId");

                    b.ToTable("Historic");
                });

            modelBuilder.Entity("haulages_bot.Models.InventoryBotConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("int");

                    b.Property<int>("SitesMax")
                        .HasColumnType("int");

                    b.Property<int>("SitesMin")
                        .HasColumnType("int");

                    b.Property<int>("TonnageMax")
                        .HasColumnType("int");

                    b.Property<int>("TonnageMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InventoryBotConfigs");
                });

            modelBuilder.Entity("haulages_bot.Models.Material", b =>
                {
                    b.Property<int>("materialTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("materialTypeId", "ServerConfigId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("haulages_bot.Models.ProductionPlanBotConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("LawMaxGrTon")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LawMaxPercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LawMinGrTon")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LawMinPercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("int");

                    b.Property<int>("TonnageMax")
                        .HasColumnType("int");

                    b.Property<int>("TonnageMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductionPlanBotConfigs");
                });

            modelBuilder.Entity("haulages_bot.Models.ProgrammingRecord", b =>
                {
                    b.Property<int>("ProgrammingRecordId")
                        .HasColumnType("int");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Dateofcarries")
                        .HasColumnType("time");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId1")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeServerConfigId")
                        .HasColumnType("int");

                    b.Property<int>("HaulageId")
                        .HasColumnType("int");

                    b.HasKey("ProgrammingRecordId", "ServerConfigId");

                    b.HasIndex("HaulageId");

                    b.HasIndex("EmployeeId1", "EmployeeServerConfigId");

                    b.ToTable("ProgrammingRecords");
                });

            modelBuilder.Entity("haulages_bot.Models.RethinkBotConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("MaxSimultaneousVehicles")
                        .HasColumnType("int");

                    b.Property<string>("RethinkHost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RethinkPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RethinkPort")
                        .HasColumnType("int");

                    b.Property<int>("ScooptramCount")
                        .HasColumnType("int");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RethinkBotConfigs");
                });

            modelBuilder.Entity("haulages_bot.Models.Route", b =>
                {
                    b.Property<int>("haulagePathId")
                        .HasColumnType("int");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("distance")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("isEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("isExtraction")
                        .HasColumnType("bit");

                    b.Property<int>("loadPointId")
                        .HasColumnType("int");

                    b.Property<string>("loadPointName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("materialType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("materialTypeId")
                        .HasColumnType("int");

                    b.Property<int>("selectedMaterialType")
                        .HasColumnType("int");

                    b.Property<decimal>("timeInHour")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("unLoadPointId")
                        .HasColumnType("int");

                    b.Property<string>("unLoadPointName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("haulagePathId", "ServerConfigId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("haulages_bot.Models.ServerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBotRunning")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSyncEnabledLocal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimezoneOffsetHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServerConfigs");
                });

            modelBuilder.Entity("haulages_bot.Models.Shift", b =>
                {
                    b.Property<int>("WorkShiftId")
                        .HasColumnType("int");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enabled")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("OperationTime")
                        .HasColumnType("time");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("WorkShiftId", "ServerConfigId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("haulages_bot.Models.TokenRegistry", b =>
                {
                    b.Property<int>("TokenRegistryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenRegistryId"));

                    b.Property<string>("access_token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("refresh_token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TokenRegistryId");

                    b.ToTable("TokenRegistries");
                });

            modelBuilder.Entity("haulages_bot.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EconomicNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EmptyWeight")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FuelTankCapacity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LoadingCapacity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("VehicleId", "ServerConfigId");

                    b.HasIndex("CompanyId", "ServerConfigId");

                    b.HasIndex("VehicleTypeId", "ServerConfigId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("haulages_bot.Models.VehicleType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleTypeId", "ServerConfigId");

                    b.ToTable("VehicleType");
                });

            modelBuilder.Entity("haulages_bot.Models.Employee", b =>
                {
                    b.HasOne("haulages_bot.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId", "ServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("haulages_bot.Models.Haulage", b =>
                {
                    b.HasOne("haulages_bot.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId1", "EmployeeServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("haulages_bot.Models.Material", "MaterialTypee")
                        .WithMany()
                        .HasForeignKey("MaterialTypeematerialTypeId", "MaterialTypeeServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("haulages_bot.Models.Vehicle", "VehicleNavigation")
                        .WithMany()
                        .HasForeignKey("VehicleNavigationVehicleId", "VehicleNavigationServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("haulages_bot.Models.Route", "HaulagePath")
                        .WithMany()
                        .HasForeignKey("haulagePathId", "HaulagePathServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Employee");

                    b.Navigation("HaulagePath");

                    b.Navigation("MaterialTypee");

                    b.Navigation("VehicleNavigation");
                });

            modelBuilder.Entity("haulages_bot.Models.Historic", b =>
                {
                    b.HasOne("haulages_bot.Models.TokenRegistry", "TokenRegistry")
                        .WithMany()
                        .HasForeignKey("TokenRegistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("haulages_bot.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId", "EmployeeServerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("haulages_bot.Models.Vehicle", "VehicleNavigation")
                        .WithMany()
                        .HasForeignKey("VehicleNavigationVehicleId", "VehicleNavigationServerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("haulages_bot.Models.Shift", "WorkShift")
                        .WithMany()
                        .HasForeignKey("WorkShiftId1", "WorkShiftServerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("haulages_bot.Models.Route", "HaulagePath")
                        .WithMany()
                        .HasForeignKey("haulagePathId", "HaulagePathServerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("haulages_bot.Models.Material", "MaterialType")
                        .WithMany()
                        .HasForeignKey("materialTypeId1", "MaterialTypeServerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("HaulagePath");

                    b.Navigation("MaterialType");

                    b.Navigation("TokenRegistry");

                    b.Navigation("VehicleNavigation");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("haulages_bot.Models.ProgrammingRecord", b =>
                {
                    b.HasOne("haulages_bot.Models.Haulage", "Haulage")
                        .WithMany()
                        .HasForeignKey("HaulageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("haulages_bot.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId1", "EmployeeServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Haulage");
                });

            modelBuilder.Entity("haulages_bot.Models.Vehicle", b =>
                {
                    b.HasOne("haulages_bot.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId", "ServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("haulages_bot.Models.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId", "ServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("VehicleType");
                });
#pragma warning restore 612, 618
        }
    }
}
