// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using haulages_bot.Data;

#nullable disable

namespace haulages_bot.Migrations
{
    [DbContext(typeof(dbboot))]
    [Migration("20260528200547_AddTimezoneOffsetToServerConfig")]
    partial class AddTimezoneOffsetToServerConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("haulages_bot.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId", "ServerConfigId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("haulages_bot.Models.DataConfigurationLocal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedEmployees")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedRoutes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedVehicles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TonnageVariation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataConfigurationLocal");
                });

            modelBuilder.Entity("haulages_bot.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaternalLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NoEmployee")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaternalLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId", "ServerConfigId");

                    b.HasIndex("CompanyId", "ServerConfigId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("haulages_bot.Models.Haulage", b =>
                {
                    b.Property<int?>("HaulageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dateofcarries")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HaulagePathServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Kilometers")
                        .HasColumnType("TEXT");

                    b.Property<string>("LawType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoadPointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoadPointName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaterialTypeeServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaterialTypeematerialTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PathId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UnloadPointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnloadPointName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VehicleNavigationServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VehicleNavigationVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.Property<int?>("haulagePathId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("materialTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HaulageId");

                    b.HasIndex("EmployeeId1", "EmployeeServerConfigId");

                    b.HasIndex("MaterialTypeematerialTypeId", "MaterialTypeeServerConfigId");

                    b.HasIndex("VehicleNavigationVehicleId", "VehicleNavigationServerConfigId");

                    b.HasIndex("haulagePathId", "HaulagePathServerConfigId");

                    b.ToTable("Haulages");
                });

            modelBuilder.Entity("haulages_bot.Models.Material", b =>
                {
                    b.Property<int>("materialTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("materialTypeId", "ServerConfigId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("haulages_bot.Models.ProgrammingRecord", b =>
                {
                    b.Property<int>("ProgrammingRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Dateofcarries")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HaulageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProgrammingRecordId", "ServerConfigId");

                    b.HasIndex("HaulageId");

                    b.HasIndex("EmployeeId1", "EmployeeServerConfigId");

                    b.ToTable("ProgrammingRecords");
                });

            modelBuilder.Entity("haulages_bot.Models.Route", b =>
                {
                    b.Property<int>("haulagePathId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("distance")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isExtraction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("loadPointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("loadPointName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("materialType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("materialTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("selectedMaterialType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("timeInHour")
                        .HasColumnType("TEXT");

                    b.Property<int>("unLoadPointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("unLoadPointName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("haulagePathId", "ServerConfigId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("haulages_bot.Models.ServerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBotRunning")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSyncEnabledLocal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerConfigs");
                });

            modelBuilder.Entity("haulages_bot.Models.Shift", b =>
                {
                    b.Property<int>("WorkShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Enabled")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("OperationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkShiftId", "ServerConfigId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("haulages_bot.Models.TokenRegistry", b =>
                {
                    b.Property<int>("TokenRegistryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("access_token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("refresh_token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("token_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TokenRegistryId");

                    b.ToTable("TokenRegistries");
                });

            modelBuilder.Entity("haulages_bot.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EconomicNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmptyWeight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FuelTankCapacity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LoadingCapacity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plates")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleId", "ServerConfigId");

                    b.HasIndex("CompanyId", "ServerConfigId");

                    b.HasIndex("VehicleTypeId", "ServerConfigId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("haulages_bot.Models.VehicleType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleTypeId", "ServerConfigId");

                    b.ToTable("VehicleType");
                });

            modelBuilder.Entity("haulages_bot.Models.Employee", b =>
                {
                    b.HasOne("haulages_bot.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId", "ServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("haulages_bot.Models.Haulage", b =>
                {
                    b.HasOne("haulages_bot.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId1", "EmployeeServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("haulages_bot.Models.Material", "MaterialTypee")
                        .WithMany()
                        .HasForeignKey("MaterialTypeematerialTypeId", "MaterialTypeeServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("haulages_bot.Models.Vehicle", "VehicleNavigation")
                        .WithMany()
                        .HasForeignKey("VehicleNavigationVehicleId", "VehicleNavigationServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("haulages_bot.Models.Route", "HaulagePath")
                        .WithMany()
                        .HasForeignKey("haulagePathId", "HaulagePathServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Employee");

                    b.Navigation("HaulagePath");

                    b.Navigation("MaterialTypee");

                    b.Navigation("VehicleNavigation");
                });

            modelBuilder.Entity("haulages_bot.Models.ProgrammingRecord", b =>
                {
                    b.HasOne("haulages_bot.Models.Haulage", "Haulage")
                        .WithMany()
                        .HasForeignKey("HaulageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("haulages_bot.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId1", "EmployeeServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Haulage");
                });

            modelBuilder.Entity("haulages_bot.Models.Vehicle", b =>
                {
                    b.HasOne("haulages_bot.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId", "ServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("haulages_bot.Models.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId", "ServerConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("VehicleType");
                });
#pragma warning restore 612, 618
        }
    }
}
